name: inference-pipeline

on:
  workflow_run:
    workflows: ["feature-pipeline"]
    types:
      - completed

  workflow_dispatch:
      
jobs:

  inference_pipeline:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: generating new batch of predictions
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: poetry run jupyter nbconvert --to notebook --execute notebooks/14_inference_feature_pipeline.ipynb